---
title: "Bird Joins"
author: "Alex Vand"
date: "8/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(lubridate)
```

## Joins on birds

```{r}
bird_observations <- read_csv(here::here("data", "52_pp52_birds_1.csv"))
sites <- read_csv(here("data", "52_pp52_sites_1.csv"))
surveys <- read_csv(here("data", "52_pp52_surveys_1.csv"))
taxalist <- read_csv(here("data", "52_pp52_taxalist_1.csv"))
```

```{r}
birds_subset <- bird_observations %>% 
  filter(species_id %in% c("BHCO", "RWBL")) %>% 
  filter(site_id %in% c("LI-W", "NU-C"))
```

```{r}
birds_left <- left_join(x = birds_subset, y = sites, by = "site_id")
birds_left <- left_join(x = birds_left, y = taxalist, by = "species_id")
```

```{r}
birds_full <- full_join(x = birds_subset, y = sites, by = "site_id")
```

```{r}
birds_inner <- inner_join(x = birds_subset, y = taxalist, by = "species_id")
left_compare <- left_join(x = birds_subset, y = taxalist, by = "species_id")
# in this particular example, output is the same
```

## Data wrangling and visualization with birds

```{r}
birds <- rename(.data = bird_observations, "bird_obs_notes" = notes) %>% 
  left_join(x = bird_observations, y = taxalist, by = "species_id") %>% 
  left_join(sites) %>% 
  left_join(surveys) %>% 
  select(survey_date, common_name, park_name, bird_count)
```

```{r}
# birds <- mutate(.data = birds, survey_date = lubridate::ymd(survey_date))

birds <- birds %>% 
  mutate(date = lubridate::ymd(survey_date)) %>% 
  mutate(month = month(date)) %>% 
  mutate(month = as.factor(month)) %>% 
  dplyr::relocate(month, .after = survey_date)
```


```{r}
bird_count <- birds %>% 
  group_by(park_name, month) %>% 
  summarize(count = n()) %>% 
  filter(park_name %in% c("Lindo", "Orme", "Palomino", "Sonrisa"))
```





